GET http://localhost:4500/users/675ddf6247783d7b274257a0
Content-Type:application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzYyODEyNThlODAxZWQ3Yjk2MzJhY2MiLCJpYXQiOjE3MzQ1MDg4Mzd9.tSIt8ZmwzdXSkddIxWiEPcYeYEI78rcUG-4qPkix2jw