// sign in with phone and password
POST http://localhost:4500/auth/user/sign-in/phone2
Content-Type:application/json
{
  "password": "ab12345678",
  "phone": "09123456789"
}

//refresh token
POST http://localhost:4500/auth/user/refresh
Content-Type:application/json

GET http://localhost:4500/users/676293d54f5c4704c82c0733
Content-Type:application/json