GET http://localhost:4500/users/675ddf6247783d7b274257a0
Content-Type:application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzYxMzYwMGQ2NzI0N2U3ODk0ZjQ5OGMiLCJpYXQiOjE3MzQ0NDU5NTl9.7dEwffbjynhzaM0ZDqRVDLkhED3YQ6QnCyBHzAUPZFg